switch logo to black white and compress logo
SpiritFour/whatsanalyze pull request #194
Opened 2021-03-09 13:13 UTC by Adrian-Thiesen

2021-03-09 13:20 UTC, PKehnel approved these changes
LGTM

2021-03-09 14:57 UTC, mowolf approved these changes
lgtm

2021-03-10 11:29 UTC, mowolf requested changes
Is this still needed?

2021-03-12 19:18 UTC, Adrian-Thiesen commented
Yes logo compressed

2021-03-13 20:25 UTC, mowolf approved these changes

2021-03-13 20:25 UTC, merged