Edit gtags
SpiritFour/whatsanalyze pull request #200
Opened 2021-03-09 14:51 UTC by Adrian-Thiesen

2021-03-09 14:59 UTC, PKehnel commented
This contains now the logo color changes, is there an agreement on this between @mowolf  and @Adrian-Thiesen?

2021-03-09 15:18 UTC, mowolf requested changes
Sorry das static/whatsanalyze-logo-white.png ist jetzt schwarz und hat unten padding?

das static/whatsanalyze-logo-white.png soll so bleiben wie davor da wir das ja an einigen stellen nutzen. Wenn du das andere irgendwo benutzen magst dann erstelle bitte eine neue Datei anstatt welche die wir benutzen zu ersetzen.

2021-03-11 15:40 UTC, fellnerse commented
is this gonna get merged at some point?

2021-03-15 13:46 UTC, closed without merging

2021-03-15 13:47 UTC, Adrian-Thiesen commented
reworked on the other gtag branch