added some information
SpiritFour/whatsanalyze pull request #224
Opened 2021-03-11 15:00 UTC by Adrian-Thiesen

2021-03-11 15:45 UTC, PKehnel commented
hier hat sich lint irgendwie gecrashed?

2021-03-11 15:46 UTC, PKehnel commented
und ein Satz kurz was sich dadruch ändert, dass du das favicon icon anders machst wäre nice. Dann ist gleich klar was passiert.

Added some infomation, ist halt schwammig ;)

2021-03-11 17:02 UTC, mowolf requested changes
Also ich finde unser logo da besser geeignet. Zudem ist das jetzt ein "1252 × 1006" favicon.png und _sollte_ ein "32x32" oder "64x64" bild sein...

Also wenn du das jetzige lassen willst dann resize das und lösche das alte...

<img width="427" alt="Bildschirmfoto 2021-03-11 um 18 00 06" src="https://user-images.githubusercontent.com/32100482/110824754-a2ea4e80-8293-11eb-8e6a-2e354e53e265.png">

2021-03-12 09:49 UTC, fellnerse commented
das linting kann man glaube ich neustarten oder?
also ich dachte wir verwenden das nur als preview, finde unser altes favicon schon besser

2021-03-15 13:50 UTC, closed without merging

2021-03-15 13:50 UTC, Adrian-Thiesen commented
not needed