Fixes
SpiritFour/whatsanalyze pull request #358
Opened 2024-01-16 22:23 UTC by mowolf

Klappt das?

2024-01-16 22:50 UTC, mowolf commented
bei mir liefs kurz, jetzt geht nix mehr...

2024-01-16 22:54 UTC, mowolf commented
bei mir läufts mit node 18

2024-01-16 22:55 UTC, mowolf commented
- [x] Bild wird auf iOS generiert bei großem chat

2024-01-16 22:58 UTC, mowolf commented
<img width="1679" alt="image" src="https://github.com/SpiritFour/whatsanalyze/assets/32100482/6183105d-891f-4c47-9ac8-3be75ad5cb2c">

iOS issue, not sure if relevant

2024-01-16 23:00 UTC, mowolf commented
![image](https://github.com/SpiritFour/whatsanalyze/assets/32100482/300d84d8-f650-488e-8777-268442f90a99)

Prozess bar for pdf is now really reflecting how much is processed

2024-01-16 23:01 UTC, mowolf commented
on iOS large chat pdf generation crashes and reloads page without error, probably memory issue

2024-01-17 08:07 UTC, fellnerse requested changes
wenn du die node version anheben willst, dann musst du das auch an allen stellen machen:
https://github.com/SpiritFour/whatsanalyze/blob/2f6449635079cd6c5fc122ec091183dc80d2a763/.github/workflows/husky.yml#L25
und allen anderen pipelines auch

und warum nicht auf node 22?

2024-01-17 08:07 UTC, fellnerse commented on pages/pwa-results.vue
> +  name: "PwaResults",
für was wird der name verwendet? ich würde das nicht ändern, wenn du das auf android nicht testen kannst

2024-01-17 08:07 UTC, fellnerse commented on package.json
> -  "husky": {
ja das kannst du bitte wieder rein tun, dein commit enthält lauter änderungen die keine sind (formatting)
musst du halt dann updaten auf node 18

2024-01-17 08:07 UTC, fellnerse commented on components/ChatVisualization/Chat.vue
> -        <v-btn
das sind alles änderungen die keine sind weil dein formatter das anders macht als das default im repo, das beim staging läuft

2024-01-17 08:07 UTC, fellnerse commented on components/ChatVisualization/PdfDownloadPopup.vue
> +        <div v-if="isLoading" class="loading mb-2"/>
warum hast du das geändert?

2024-05-31 07:29 UTC, fellnerse approved these changes
fertig

2024-05-31 07:39 UTC, merged